services:
  postybirb:
    image: leaftail/postybirb-v4-alpha-headless:latest
    ports:
      - 8080:8080
    tty: true
    attach: true
    entrypoint: ./node_modules/.bin/electron . --headless --port=8080
